wso2/wso2-axis2

modules/kernel/src/org/apache/axis2/transport/http/HTTPConstants.java, modules/transport/http/src/org/apache/axis2/transport/http/HTTPTransportUtils.java
https://wso2.org/jira/browse/CARBON-15130
=> Added support for application/jwt Content-Type

modules/json/src/org/apache/axis2/json/gson/JSONMessageHandler.java, modules/json/test/org/apache/axis2/json/gson/JSONMessageHandlerTest.java
Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>
=> Adding fix for CARBON-15089.

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java, modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamWriter.java, modules/json/src/org/apache/axis2/json/gson/factory/JsonConstant.java
Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>
=> Adding fix for CARBON-15077

modules/metadata/test/org/apache/axis2/jaxws/description/impl/ParameterDescriptionImplTests.java, modules/parent/pom.xml, modules/testutils/src/main/java/org/apache/axis2/testutils/RuntimeIgnoreRunNotifier.java
Signed-off-by: Jayanga Dissanayake <jsdjayanga@gmail.com>
=> Fixing testcase failures due to execution order.

modules/json/src/org/apache/axis2/json/AbstractJSONMessageFormatter.java
will add Integration tests to the kernel4
=> fixed JIRA CARBON-15261

modules/kernel/src/org/apache/axis2/dispatchers/HTTPLocationBasedDispatcher.java
fixed the index of ServiceName in parseRequestURL method to set the HTTP Location
=> fixed the index of ServiceName

modules/json/src/org/apache/axis2/json/gson/factory/XmlNodeGenerator.java
fix for JIRA : https://wso2.org/jira/browse/DS-1047
=> NPE fixed for simple type elements

modules/json/test/org/apache/axis2/json/gson/JSONXMLStreamAPITest.java, modules/json/test/org/apache/axis2/json/gson/rpc/JSONRPCIntegrationTest.java, modules/testutils/src/main/java/org/apache/axis2/testutils/UtilServer.java
where simplehttpserver connection is refused. Also added a log if the server started to fail.
+ minor code styling
=> Providing possible fix for intermediate test issue

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
Jira - https://wso2.org/jira/browse/CARBON-15714
=> [CARBON-15714] Multipart form data formatter bug fix

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java, modules/json/test-resources/custom_schema/testSchema_3.xsd, modules/json/test/org/apache/axis2/json/gson/GsonXMLStreamReaderTest.java
DS-1190-Value type missmatch error when invoking services with Numeric/Blob types
=> DS-1190-Value type missmatch error when invoking services with Numeric/Blob types

modules/kernel/src/org/apache/axis2/util/Utils.java
https://wso2.org/jira/browse/ESBJAVA-4014
=> Fixing the ESBJAVA-4014 issue

modules/kernel/src/org/apache/axis2/util/Utils.java
=> Revert "Fixing the ESBJAVA-4014 issue"

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java
=> Fix NPE in validateArgumentTypes method

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamWriter.java, modules/json/src/org/apache/axis2/json/gson/factory/XmlNodeGenerator.java
Resolves https://github.com/wso2/wso2-axis2/issues/108
=> Fix json support for DSS Request Box

modules/transport/http/src/org/apache/axis2/transport/http/HTTPSender.java
This is a new PR for #94 which had to be sent to master branch.
This is a fix for https://wso2.org/jira/browse/CARBON-16056
=> Fix response status code not handled correctly

orbit/axis2-client/pom.xml, orbit/axis2-jaxbri/pom.xml, orbit/axis2-json/pom.xml, orbit/axis2/pom.xml
=> Fix orbit bundle version inconsistency

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java, modules/kernel/test-resources/binaryFile.xml, modules/kernel/test/org/apache/axis2/transport/http/MultipartFormDataFormatterTest.java
Public jira - https://wso2.org/jira/browse/ESBJAVA-5041
=> Fix issue of header is getting modified when posting multipart/form-data

modules/kernel/src/org/apache/axis2/transport/http/HTTPConstants.java, modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java
[https://wso2.org/jira/browse/ESBJAVA-5225](https://wso2.org/jira/browse/ESBJAVA-5225)
EI Tests: [https://github.com/wso2/product-ei/pull/1068](https://github.com/wso2/product-ei/pull/1068)
=> ESBJAVA-5225: Add default Content-Type conditionally

modules/transport/base/src/main/java/org/apache/axis2/transport/base/AbstractTransportListenerEx.java
Fix ESB-5.0.0 intemittent TcpTransportProxyServiceTestCase test failure. …
=> Fix for intermittent class not found CarbonJavaURLContextFactory

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java
Content-Type:0 in header causes checkContentLength method to return false in handleResponse and as a consequence causes NullPointerException in Axis2Sender.sendBack method. It occurs for example when service reply with error code (409 Conflict) and Content-Length set on 0 value.
=> Protect from Content-Type:0

pom.xml
Changed parent pom from org.apache to org.wos2
=> Change parent pom from org.apache to org.wso2

modules/kernel/src/org/apache/axis2/description/ClientUtils.java
It can go to OOM  if sending a message out failed continousely. This is happened as the operation context is accumilated and never cleanup until sending message out successfully.
This PR is to cleanup operation context, for failure cases.
The related issue is wso2/product-ei#2197
> …
=> Cleanup operation context for failures

modules/kernel/src/org/apache/axis2/description/ClientUtils.java
This is to fix https://github.com/wso2/product-ei/issues/2211
> Link(s) to product documentation that addresses the changes of …
=> Fix NPE when Address information does not exist in the Endpoint Reference

modules/kernel/src/org/apache/axis2/description/AxisEndpoint.java, modules/kernel/src/org/apache/axis2/description/AxisService2WSDL11.java
This is to hide endpoint urls in wsdl for the endpoints other than http, https or tcp to fix [1]
[1] https://github.com/wso2/product-ei/issues/2602
> Brief description of the new feature or bug fix as it will appear …
=> Fix EI-2602

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java
> Fix is related to product-ei/issues/2709
This fixes the issue when building the message when the response is 204 No Content.
> …
=> Fix is related to product-ei/issues/2709

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java
> This is to prevent from NPE.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Adding a null check

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
Fixes the issue of encoding the multipart message when the message
get builds.
Resolves: wso2/product-ei#
=> Fix EI-1525

modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java
Fix https://github.com/wso2/product-ei/issues/3212
=> Disable http client retry

modules/fastinfoset/pom.xml, modules/kernel/pom.xml, modules/parent/pom.xml, modules/tool/axis2-aar-maven-plugin/pom.xml, modules/tool/axis2-ant-plugin/pom.xml, orbit/axis2-client/pom.xml
> To change http-commons dependency. …
=> Axis2 java11

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamWriter.java
This is to add intuitive error messages in json formatter. Currently if the resultset does not match with the service schema it gives an exception : javax.xml.stream.XMLStreamException: Invalid Staring element.
Therefore, it is hard to identify the actual root cause.
https://github.com/wso2/product-ei/issues/2379
> Brief description of the new feature or bug fix as it …
=> Add intuitive error messages in json formatter

modules/adb/pom.xml, modules/corba/pom.xml, modules/jaxws-integration/pom.xml, modules/jaxws/pom.xml, modules/osgi/pom.xml, modules/parent/pom.xml, modules/samples/jaxws-addressbook/pom.xml, modules/samples/jaxws-calculator/pom.xml, modules/samples/jaxws-version/pom.xml, modules/tool/axis2-idea-plugin/pom.xml, orbit/axis2/pom.xml
> Revert java-11 release related commits to do a release that would be used as a dependency for a wso2-kernel release. (wso2-kernel release will not be supporting java 11, hence no requirement to add java-11 related changes into wso2-axis2 release). The reverted commit will be merged back after the release.
> Brief description of the new feature or bug fix as it will …
=> Reverting java-11 related commits

orbit/axis2-client/pom.xml
Reverts wso2/wso2-axis2#152
( To do the wso2-axis2 release for kernel 4.4.37 release)
=> Revert " Add javax.activation dependency"

modules/kernel/src/org/apache/axis2/util/MessageProcessorSelector.java
Fix the issue of applying ContentType property with disabled chunking.
Fix https://github.com/wso2/product-ei/issues/3315
> Link …
=> Fix product-ei#3315

modules/parent/pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Upgrade Google Gson version

modules/fastinfoset/pom.xml, modules/kernel/pom.xml, modules/parent/pom.xml, modules/tool/axis2-aar-maven-plugin/pom.xml, modules/tool/axis2-ant-plugin/pom.xml, orbit/axis2-client/pom.xml
Update commons http clint to compatible version
=> Update commons http clint to compatible version

modules/parent/pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Upgrade version

modules/kernel/pom.xml, orbit/axis2-client/pom.xml
> Change securevault version to `1.1.2` in axis2.
=> Change securevault version in axis2.

modules/adb/src/org/apache/axis2/databinding/utils/BeanUtil.java
This PR fixes the issue https://github.com/wso2/product-apim/issues/4697
=> Fix printing BeanUtil Cannot find the field UUID error

modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java
=> Fix content-type header change for multipart/form-data

modules/kernel/src/org/apache/axis2/deployment/AxisConfigBuilder.java
Add secure-vault related changes
=> Add secure-vault related changes

orbit/axis2-client/pom.xml
=> Add javax.activation dependency

modules/adb/pom.xml, modules/corba/pom.xml, modules/jaxws-integration/pom.xml, modules/jaxws/pom.xml, modules/osgi/pom.xml, modules/parent/pom.xml, modules/samples/jaxws-addressbook/pom.xml, modules/samples/jaxws-calculator/pom.xml, modules/samples/jaxws-version/pom.xml, modules/tool/axis2-idea-plugin/pom.xml, orbit/axis2/pom.xml
=> Adding back java-11 related commits

modules/parent/pom.xml
=> update axiom version

modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java
Fixed the faulty response received in JMS dual channel scenario when JMS service returns content-type as text/XML 
Related issue: https://github.com/wso2/product-apim/issues/4807
=> Fixed the missing SOAP envelopes issue in the response during JMS flow

modules/transport/http/src/org/apache/axis2/transport/http/HTTPSender.java
Fixes https://github.com/wso2/product-ei/issues/4430
=> Fix https://github.com/wso2/product-ei/issues/4430

modules/adb/src/org/apache/axis2/databinding/utils/ConverterUtil.java
=> Fix syntax errors in error message

modules/saaj/src/org/apache/axis2/saaj/util/SAAJUtil.java
> Implement secure use of DocumentBuilderFactory in compliance with WSO2 secure engineering guidelines [1] to fix improper restriction of External XML Entity (XXE) Reference.
[1] https://wso2.com/technical-reports/wso2-secure-engineering-guidelines
=> Fix improper restriction of XXE

modules/kernel/src/org/apache/axis2/deployment/AxisConfigBuilder.java, modules/kernel/src/org/apache/axis2/deployment/DescriptionBuilder.java
> This PR will be add environment variable support for axis2 configuration file.
Fix : https://github.com/wso2/product-ei/issues/4724
=> Add environment variable support for axis2 configuration

modules/kernel/src/org/apache/axis2/Constants.java, modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java
**Proposed changes in this pull request**
- Fix comments in the PR[1]
[1] - https://github.com/wso2/wso2-axis2/pull/154
=> Fix comments.

modules/kernel/src/org/apache/axis2/deployment/repository/util/WSInfoList.java
Fixed https://github.com/wso2/product-apim/issues/7353
=> Fixed https://github.com/wso2/product-apim/issues/7353

modules/kernel/src/org/apache/axis2/Constants.java, modules/kernel/src/org/apache/axis2/transport/http/ApplicationXMLFormatter.java, modules/kernel/src/org/apache/axis2/transport/http/SOAPMessageFormatter.java, modules/transport/base/src/main/java/org/apache/axis2/format/PlainTextFormatter.java
This PR would enable setCharacterEncoding property for nhttp transport
Fix wso2/product-ei#4970
=> Fix issue setCharacterEncoding property not available in nhttp transport

modules/kernel/src/org/apache/axis2/description/AxisResource.java, modules/kernel/src/org/apache/axis2/description/AxisResourceMap.java, modules/kernel/src/org/apache/axis2/description/AxisResourceParameter.java, modules/kernel/src/org/apache/axis2/description/AxisResources.java
>Add set of beans to represnt an API.
Add an interface to expose the API definition.
Fixes /wso2/product-ei/issues/4999
=> Add set of beans to define an API.

pom.xml
> Change maven release URLs to HTTPS
=> Change maven release URLs to HTTPS

modules/transport/http/src/org/apache/axis2/transport/http/HTTPSender.java
- Add capability for 'non.error.http.status.codes' property to be configured in the synapse configuration as a comma-separated string.
- The ability to configure the property as a Set in a class mediator is still supported for backward compatibility.
- Resolves wso2/product-ei#5022
=> Ability to configure 'non.error.http.status.codes' as a property in Synapse

modules/transport/base/src/main/java/org/apache/axis2/transport/base/AbstractTransportSender.java
> This PR will fix will consider out-in, in-out MEP to wait for synchronous response.
=> Consider out-in, in-out MEP to wait for synchronous response

modules/kernel/src/org/apache/axis2/deployment/AxisConfigBuilder.java, modules/kernel/src/org/apache/axis2/deployment/DescriptionBuilder.java, modules/kernel/src/org/apache/axis2/deployment/util/Utils.java
$Subject
Fixes https://github.com/wso2/product-ei/issues/5054
=> Environment variable support for axis2 transportSenders and transportReceivers

modules/parent/pom.xml, orbit/axis2-client/pom.xml, orbit/axis2-jaxbri/pom.xml, orbit/axis2-jibx/pom.xml, orbit/axis2-json/pom.xml, orbit/axis2/pom.xml
Upgrades the distrbutionManagement urls to https due to the time taken for deploying artifacts.
=> Update http urls to https

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
This PR is to fix wso2/product-ei#5109
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Fix EI-5109: Elements in the multipart formdata are not constructed properly

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java
=> Revert "Fix issue when empty payload returned with 201 status code"

modules/parent/pom.xml, orbit/axis2-client/pom.xml
=> Upgrade httpcore dependency version

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
Fixes: https://github.com/wso2/product-ei/issues/5376
=> Fix null pointer issue when sending multipart request

modules/kernel/src/org/apache/axis2/transport/http/util/URIEncoderDecoder.java
Fix the issue in Charset being encoded with UTF-8 with DSS.
Fixes wso2/product-ei#5261
=> Fix the issue in Charset encoding with DSS

modules/kernel/src/org/apache/axis2/deployment/util/Utils.java
This PR will remove the org.apache.commons.lang3.StringUtils dependency from the axis2.
> Link(s) to product documentation that …
=> Remove StringUtills dependency from Utills

modules/kernel/src/org/apache/axis2/description/AxisMessage.java
=> Fix NPE while getting schema of the service

modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java
=> Set host config protocol while setting the host

modules/parent/pom.xml, modules/transport/base/pom.xml, orbit/axis2-client/pom.xml, orbit/axis2-jaxbri/pom.xml, orbit/axis2-jibx/pom.xml, orbit/axis2-json/pom.xml, orbit/axis2/pom.xml
Update maven bundle plugin and set maven deploy plugin
To make this repo align with the other repos. Specially when considering the bundle manifests
Update maven bundle plugin and set maven deploy plugin
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Update maven bundle plugin and set maven deploy plugin

modules/kernel/src/org/apache/axis2/Constants.java, modules/kernel/src/org/apache/axis2/builder/ApplicationXMLBuilder.java, modules/kernel/src/org/apache/axis2/transport/http/ApplicationXMLFormatter.java
Introduced a new axis2 property(**PRESERVE_XML_PROCESSING_INSTRUCTIONS**) to enforce preserving the xml processing instructions.
If the property is set only, the xml processing instructions in the original response will be preserved and sent to the client.
Fixes: wso2/micro-integrator#2347
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is …
=> Introduce property to preserve xml processing instructions in XML formatter

modules/kernel/src/org/apache/axis2/util/MultipleEntryHashMap.java
Fixes: https://github.com/wso2/product-apim/issues/11517
=> Fix APIMINTERNAL-872

modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java
$subject
Related to wso2/product-ei#5462
=> Handle NPE when null header values are received

modules/parent/pom.xml, orbit/axis2-client/pom.xml, orbit/axis2-json/pom.xml, orbit/axis2/pom.xml
Related issues wso2/product-is#12485
> Update xmlbeans version to 3.0.0
=> Dependency version update axis2.

modules/kernel/pom.xml, modules/parent/pom.xml, modules/transport/base/pom.xml, modules/transport/http/pom.xml, orbit/axis2-client/pom.xml, orbit/axis2-jaxbri/pom.xml, orbit/axis2-jibx/pom.xml, orbit/axis2-json/pom.xml, orbit/axis2/pom.xml, pom.xml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Change repo URLs to https in pom.xml files of master

orbit/axis2-jaxbri/pom.xml
Pack jaxbri classes in the bundle
Pack jaxbri classes in the bundle
Add OSGi private package tag
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Add OSGi private package to module axis2-jaxbri

modules/parent/pom.xml, orbit/axis2-client/pom.xml, orbit/axis2/pom.xml
=> Bump xmlbeans version to 3.1.0

modules/kernel/pom.xml, modules/kernel/src/org/apache/axis2/util/PrettyPrinter.java, orbit/axis2-client/pom.xml, pom.xml
Resolves https://github.com/wso2/product-apim/issues/12205
=> Removing log4j usages

modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java, modules/kernel/src/org/apache/axis2/builder/MultipartFormDataBuilder.java, modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
Git issue:
https://github.com/wso2/product-apim/issues/11895
https://github.com/wso2/product-apim/issues/12000
> Link to the PR …
=> Fixing charset issue in multipart form data request flow

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
Fixes https://github.com/wso2/product-ei/issues/5544
=> Add correct charset for file part requests

modules/transport/base/src/main/java/org/apache/axis2/format/PlainTextBuilder.java
> Fixing https://github.com/wso2/product-apim/issues/12522
=> Fixing product-apim/issues/12522

modules/parent/pom.xml
=> Bump gson version

modules/kernel/src/org/apache/axis2/engine/AxisEngine.java
> Increase accessibility of the flowComplete method
> Change access modifier of the flowComplete method in AxisEngine class to **protected**
=> Increase accessibility of flowComplete method

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
This PR would enable setCharacterEncoding property in MultipartFormDataFormatter
Fixes: https://github.com/wso2/api-manager/issues/765
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Enable setCharacterEncoding property in MultipartFormDataFormatter

modules/parent/pom.xml
- $subject to 1.2.11-wso2v26[1]
[1] https://github.com/wso2/wso2-axiom/tree/v1.2.11-wso2v26
=> Update axiom version to the latest release

modules/parent/pom.xml
- $subject the fileupload changes in [1]
[1] https://github.com/wso2/wso2-axis2/pull/266
=> Revert fileupload version to 1.3.1.wso2v1

modules/parent/pom.xml
- $subject
- https://github.com/wso2/wso2-axis2/pull/266
=> Revert axiom version bump

modules/kernel/src/org/apache/axis2/deployment/RepositoryListener.java, modules/kernel/src/org/apache/axis2/deployment/repository/util/WSInfoList.java
$subject. Resolves https://github.com/wso2/api-manager/issues/1320
=> Add implementation to stop service un-deployment, upon an IO error when listing files of a directory

modules/java2wsdl/pom.xml, modules/jaxws/pom.xml, modules/parent/pom.xml
=> Revert "Removes apache xalan library"

modules/kernel/src/org/apache/axis2/Constants.java, modules/kernel/src/org/apache/axis2/context/ConfigurationContext.java, modules/kernel/src/org/apache/axis2/context/ConfigurationContextFactory.java, modules/kernel/src/org/apache/axis2/dispatchers/RequestURIBasedServiceDispatcher.java, modules/kernel/src/org/apache/axis2/util/Utils.java
> Strictly check the service URL to starts with service path. 
And added a parameter to enable the check.
Fixes wso2/micro-integrator/issues/2935
=> Introduce strict service path validation

modules/kernel/src/org/apache/axis2/Constants.java, modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java, modules/kernel/src/org/apache/axis2/transport/http/util/ComplexPart.java
> Fixes https://github.com/wso2/api-manager/issues/2186
=> Fix the issue of incorrect splitting when sending an attachment on a Soap Service exposed as Rest Api using multipart form data

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java
This is to revert https://github.com/wso2/wso2-axis2/pull/276
> Link(s) to product documentation that addresses the changes of …
=> Avoid adding charset only when setCharacterEncoding property is false

modules/adb/src/org/apache/axis2/databinding/utils/ConverterUtil.java
Fix wso2/micro-integrator#3273
When the Calendar instance is initiated using the default timezone, it automatically incorporates the DST offset. Hence the DST offset in the calendar is set to zero.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Fix timestamp conversion failure

modules/parent/pom.xml, orbit/axis2-client/pom.xml
This PR upgrades the commons-fileupload version to a non-vulnerable version.
=> Upgrade commons-fileupload version

modules/parent/pom.xml
$subject
Related issue: https://github.com/wso2/product-is/issues/21200 …
=> Upgrade axiom version to 1.2.11-wso2v29

modules/parent/pom.xml
$subject
Related PR: https://github.com/wso2/wso2-axis2/pull/287 …
=> Revert axiom version upgrade

modules/transport/base/pom.xml
$subject
Related issue
- https://github.com/wso2/product-is/issues/21200 …
=> Upgrade commons-io version to 2.17.0

modules/transport/base/pom.xml
$subject
Related PR: https://github.com/wso2/wso2-axis2/pull/290 …
=> Revert commons-io version upgrade

modules/parent/pom.xml, modules/transport/base/pom.xml, orbit/axis2-client/pom.xml
Upgrade commons-fileupload and commons-io versions
=> Upgrade commons-fileupload and commons-io versions
