wso2/wso2-axis2

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamWriter.java
modules/json/src/org/apache/axis2/json/gson/JsonFormatter.java
modules/json/test/org/apache/axis2/json/gson/GsonXMLStreamWriterTest.java

XML result only has a parent wrapper element, and no child sub elements. the org.apache.axis2.json.gson.JsonFormatter is giving a fault message, rather than returning an empty object

Fixing CARBON-15112

---

modules/integration/test/org/apache/axis2/transport/http/CARBON15646CommonsTransportHeadersTest.java
modules/integration/test/org/apache/axis2/transport/http/CARBON15646CommonsTransportHeadersTestCase.java
modules/transport/http/src/org/apache/axis2/transport/http/CommonsTransportHeaders.java

When IS is in a distributed setup fronted by a load balancer, when accessing the dashboard a 401 error occurs due to an AXIS2 bug which causes it to return only one cookie where there are two cookies 
including the one set by the load balancer.
This fix was introduced to solve the above issue.
https://wso2.org/jira/browse/CARBON-15646

CARBON-15646: Return multiple Set-Cookies

---

modules/kernel/src/org/apache/axis2/transport/http/SOAPMessageFormatter.java

Fix Soap part comes as attachment when a content aware mediator is in out sequence
`org.apache.axiom.attachments.Attachments#getAllContentIDs` will return the content IDs including the content ID of the SOAP part. So when need to exclude the SOAPPartContentId when creating the attachments.

Fix ESBJAVA-5072

---

modules/integration/test/org/apache/axis2/transport/http/MultipartFormDataFormatterTest.java
modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java

This introduces a dedicated XML tag that we can use to indicate a
file field. The proposed format is mentioned below.
```xml
<root>
<customFieldOne>$1</customFieldOne>
<customFieldTwo>$2</customFieldTwo>
<file name="fieldname" filename="sample-file.txt" content-type="text/plain" charset="US-ASCII" xmlns="http://ws.apache.org/ns/synapse/form-data"></file>
</root>
```
https://wso2.org/jira/browse/CARBON-16121
Resolves #101

Add file field support for content-type "multipart/form-data"

---

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamWriter.java

This pull request resolves https://wso2.org/jira/browse/DS-1272
In this fix, we skip inner elements when the parent element is not available. therefore what we have done in the fix is we check the parent element and skip the inner elements.

Fix Invalid Staring element issue in nested elments

---

modules/adb/src/org/apache/axis2/databinding/utils/BeanUtil.java

This PR fixes thread blocking issue in calling admin services with high concurrency.
Resolves #109

Fix thread block in BeanUtil class

---

modules/json/src/org/apache/axis2/json/gson/JsonBuilder.java

Change the primary logging in org.apache.axis2.json.gson.JsonBuilder to JCL and bridge to Log4J.
Resolves #111

Fix direct use of Log4J in JsonBuilder

---

modules/transport/base/src/main/java/org/apache/axis2/transport/base/AbstractTransportListenerEx.java

Fix class not found org.apache.activemq.jndi.ActiveMQInitialContextFactory error at jms listener start using MBean. Issue found was, listener's polling task threads created at start has a class loader which cannot identify the ActiveMQInitialContextFactory class. Threads created at start, get the class loader of the current thread which comes with the request from MBean.
Fixed: https://github.com/wso2/product-ei/issues/1189
As the fix, we set the classloader of the current class which can recognize ActiveMQInitialContextFactory class, before creating the polling task threads. 
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A

EI#1189: Fix for class not found ActiveMQInitialContextFactory

---

modules/transport/http/src/org/apache/axis2/transport/http/HTTPSender.java
modules/transport/http/src/org/apache/axis2/transport/http/PatchMethod.java

> Add HTTP PATCH method support to HTTPSender class.
> Fixes ESBJAVA-5126
> Create new HTTP method PATCH which was not supported in commons-httpclient:3.1
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

Fix for ESBJAVA-5126

---

modules/kernel/src/org/apache/axis2/transport/http/ApplicationXMLFormatter.java
modules/kernel/test/org/apache/axis2/transport/http/util/XMLDeclarationTest.java

Introduced a new axis2 property(WRITE_XML_DECLARATION) to enforce the xml declaration.
If it is set the output xml will contain xml declaration.
Resolve https://github.com/wso2/product-ei/issues/1629
To get XML declaration in the output
Added XML declaration for the formatter output 
Introduced a new axis2 property(WRITE_XML_DECLARATION) to determine whether the XML declaration is need or not 
N/A
N/A
This fix introduces  3 new axis2 scope properties
- **WRITE_XML_DECLARATION** 
Determine whether the XML declaration is needed or not 
- **XML_DECLARATION_ENCODING**
The value of the Encoding attribute appears in the XML declaration, if this is not set, default encoding will be added to the declaration.
- **XML_DECLARATION_STANDALONE**
The value of the standalone attribute appears in the XML …

Add XML declaration support for XML formatter

---

modules/transport/base/src/main/java/org/apache/axis2/transport/base/AbstractTransportSender.java
modules/transport/base/src/test/java/org/apache/axis2/transport/base/AbstractTransportSenderTest.java

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Fix issue https://github.com/wso2/product-ei/issues/1036

---

modules/transport/http/src/org/apache/axis2/transport/http/CommonsHTTPTransportSender.java

Set connection/socket timeout values to connection manager to use it later..
> Make possible to use timeout values later.
> Set connection/socket timeout values to connection manager.
The timeout value is set to a variable, but it is not passed to the Connection manager.
```
Parameter tempSoTimeoutParam = transportOut
.getParameter(HTTPConstants.SO_TIMEOUT);
Parameter tempConnTimeoutParam = transportOut
.getParameter(HTTPConstants.CONNECTION_TIMEOUT);
if (tempSoTimeoutParam != null) {
soTimeout = Integer.parseInt((String) tempSoTimeoutParam
.getValue());
}
if (tempConnTimeoutParam != null) {
connectionTimeout = Integer
.parseInt((String) tempConnTimeoutParam.getValue());
}
```
So I added parameter setting code..
```
connectionManager.getParams().setSoTimeout(soTimeout); …
```

Set connection/socket timeout values

---

modules/transport/local/src/org/apache/axis2/transport/local/LocalTransportReceiver.java

Fixes: https://github.com/wso2/product-ei/issues/2173
This issue is fixed by adding the message id of the incoming message
context to the newly created message context within
LocalTransportReceiver
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> jdk 1.8.0_144 EI-6.2.0

Fix wso2/product-ei/issues/2173

---

modules/json/src/org/apache/axis2/json/gson/GsonXMLStreamReader.java
modules/json/test-resources/custom_schema/testSchema_4.xsd
modules/json/test-resources/custom_schema/testSchema_5.xsd
modules/json/test/org/apache/axis2/json/gson/GsonXMLStreamReaderTest.java

> It is required that the request method and resource to be included in the payload body when a JSON payload is sent to a dataservice. Only if the exact request path is available in the payload then only the payload will be executed.(_postemployee_batch_req,_postemployee).
JSON payload is taken as an input stream and sent to GsonStreamReader , reading of values and validation of payload takes place here. JSON payload is validated against a schema which contains the format for the json payload.
When the element name is change than that of the schema validation fails and the operation breaks at GsonStreamReader.
Resolves: https://github.com/wso2/product-ei/issues/2722
>Allow the payload to be executed without the requirement of request name to be available in the json payload ie: allow …

Fix product-ei/issues/2722

---

orbit/axis2-client/pom.xml
orbit/axis2-jaxbri/pom.xml
orbit/axis2-json/pom.xml
orbit/axis2/pom.xml

Fix the build break due to maven-surefire version
Fix the build break due to maven-surefire version
Set a compatible maven-surefire version.
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
N/A
- Integration tests
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? N/A
- Ran FindSecurityBugs plugin and verified report? N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? N/A
N/A
N/A
N/A
N/A
N/A

Add maven-surefire version to orbit pom file

---

orbit/axis2-client/pom.xml

From onwards java 11 the javax.activation package has been removed from the runtime. This dependency is needed during the stub file generation. 
Add javax.activation dependency
merge after : https://github.com/wso2/orbit/pull/339

 Add javax.activation dependency

---

modules/kernel/src/org/apache/axis2/util/Utils.java

> It is not possible to invoke a proxy service using /services/proxyName/services/xxx url because of the 2nd "services" wording within url. It will only invoke the default main sequence.
The issue is with the check where it takes the lastIndexOf the "/services/". Fix it for taking the index of the first occurrence using "indexOf" method.

Fix wso2/product-ei/issues/3062

---

modules/adb/src/org/apache/axis2/databinding/annotation/IgnoreNullElement.java
modules/adb/src/org/apache/axis2/databinding/utils/BeanUtil.java
modules/kernel/src/org/apache/axis2/Constants.java
modules/transport/http/pom.xml
modules/transport/http/src/org/apache/axis2/transport/http/AxisServlet.java

When a new attribute is added to an Admin Service (WSDL) then the existing clients that have not regenerated the stub will get an error "Unexpected Subelement" when trying to access a service that will return the new attribute.
Introduce a new annotation that will skip null values after chacking a system property. For clients who do not need to skip null values can assign the new system property in the server startup.
- Add a custom annotation `IgnoreNullElement` to skip null values.
- Check the annotation and a system property `forceIncludeNullElements` when creating the `PropertyQnameList`.
- If the property value is null, `IgnoreNullElement` annotation is set and the `forceIncludeNullElements` is not set then skip  adding the property in the `PropertyQnameList`.

Add a custom annotation to skip null values.

---

modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java

Purpose
> Fixes: wso2/product-ei#4379
> EI should be able to handle multipart requests without content-type 
> Use default content-type

Fix [EI-4379] NPE thrown for multipart requests

---

orbit/axis2/pom.xml

This fix the issue - https://github.com/wso2/product-is/issues/6770
> Our intention is to move both javax.xml.soap and com.sun.xml move to same class loader lib

Change javax.xml.soap import-package version

---

modules/kernel/src/org/apache/axis2/Constants.java
modules/kernel/src/org/apache/axis2/deployment/DescriptionBuilder.java

> This PR updates the replaceSystemProperty() method. The environment variables can be defined as $env{ref} and the system properties can be defined as $sys{ref} in axis2 configuration.

Update replaceSystemProperty method to support resolving $env and $sys

---

modules/transport/base/src/main/java/org/apache/axis2/transport/base/IgnoreSuspensionBaseTransportException.java

The JMS endpoints in request-response service (JMS dual-channel proxy service )
will immediately suspend when it receives a malformed JMS message (The type which).
Fix this by introducing a new error_code 101550. To differentiate this in synapse level
this new exception is introduced
Related: https://github.com/wso2/product-ei/issues/5047s

Fix: https://github.com/wso2/product-ei/issues/5047

---

modules/transport/base/src/main/java/org/apache/axis2/transport/base/BaseConstants.java

For the use of the Transaction counting mechanism, a new property called "INTERNAL_TRANSACTION_COUNTED" is introduced, which will be checked by the "handleRequestInFlow(MessageContext messageContext)" method inside the synapse handler called "TransactionHandler". If the property is already there in the request with the relevant value, the transaction will be counted.

Introduce "internalTransaction" property to the message context

---

modules/transport/http/src/org/apache/axis2/transport/http/HTTPSender.java

Resolves wso2/wso2-axis2#211
Use following property to avoid sending cookie headers along with the request.
```
<property name="DISABLE_COOKIE" value="true" scope="axis2" type="BOOLEAN"/>
```
Support for `DISABLE_COOKIE` property for `PATCH` requests
https://github.com/wso2/docs-ei/issues/1600

Fix for wso2/wso2-axis2#211

---

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java

Fix this issue by reading ahead one byte from the input stream and
decide whether it is empty or not prior to building
(when 201 and 202 returns as response HTTP status code).
Fixes: https://github.com/wso2/product-ei/issues/5251
Fixes: https://github.com/wso2/product-ei/issues/4811
Alter fix for https://github.com/wso2/product-ei/issues/4695

Fix issue when empty payload returned with 201 status code

---

modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java

Resolves wso2/micro-integrator#2092
Use a System parameter to preserve Headers in axis2 blocking transport.
System parameter : `-Dhttp.headers.preserve=<CommaSeperatedHeaderList>`

Allow headers to be preserved in blocking transport

---

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java

Reverts wso2/wso2-axis2#218
Commit bec3fa90b61058cfe94c790997c961e611fe2494, improves the fix to handle empty payload response for HTTP 200 status code.
Related synapse PR https://github.com/wso2/wso2-synapse/pull/1775

Revert "Revert "Fix issue when empty payload returned with 201 status code"" and add fix for HTTP status code 200

---

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java

This PR removes HTTP Status code 200 from the canResponseHaveBody method that was introduced from the PR https://github.com/wso2/wso2-axis2/pull/225
We will be introducing a configuration element to allow HTTP status code 200 empty body response (in blocking mode).

Update PR https://github.com/wso2/wso2-axis2/pull/225

---

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java

This PR introduces a system property **allowEmptyBodyForHttp2xx** to allow receiving empty body for HTTP status code 200, 201, 202 (for blocking calls)
Fixes https://github.com/wso2/product-ei/issues/5251

Introduce a system property to allow empty body for Http response in blocking mode

---

modules/integration/test/org/apache/axis2/transport/http/MultipartFormDataFormatterTest.java
modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java
modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java

Fixes: https://github.com/wso2/product-apim/issues/12361
Fixing the Content-Type is being sent as "charset" for binary content-types like application/pdf (which does not have a direct charset associated with it)
When the charset is not included in the content type, the charset will be set to DEFAULT_CHARSET in createMultipatFormDataRequest function

Fixing the Content-Type is being sent as "charset" for binary content-types like application/pdf

---

modules/kernel/src/org/apache/axis2/builder/BuilderUtil.java
modules/kernel/src/org/apache/axis2/builder/MultipartFormDataBuilder.java
modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java

To fix changing the Content-Type when building the message before sending it to the backend.
Fixes: https://github.com/wso2/api-manager/issues/120
Introduced a new attribute from MultipartFormDataBuilder

Fix changing Content-Type when build the message before sending to the backend

---

modules/integration/test/org/apache/axis2/transport/http/CommonsTransportHeadersTest.java
modules/transport/http/src/org/apache/axis2/transport/http/CommonsTransportHeaders.java

Use of `java.util.TreeMap` over `java.util.HashMap` to avoid header values getting overwritten by others. 
Related issue: https://github.com/wso2/product-ei/issues/5472

Set transport headers map case insensitive in CommonsTransportHeaders class

---

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java

>  Fixes the issue where client receives a response without namespace ('xmlns") while retrieving data of the multipart/form-data content type using the multipart/form-data message builder and formatter. 
> Git Issue: https://github.com/wso2/api-manager/issues/1751

Add missing namespace in multipart/form-data response

---

modules/kernel/src/org/apache/axis2/transport/TransportSender.java

Added a new method to the TransportSender interface to let the Application layer notify the transport layer about errors. This method will be overridden by specific transports to handle the error scenarios.
Fixes: https://github.com/wso2/api-manager/issues/1746

Added a new method to the TransportSender interface to let the Application layer notify the transport layer about errors

---

modules/kernel/src/org/apache/axis2/transport/http/MultipartFormDataFormatter.java

This PR would enable setCharacterEncoding property in MultipartFormDataFormatter
When the setCharacterEncoding property is not set, character encoding would not be added.
Ported from: https://github.com/wso2-support/wso2-axis2/pull/386
Resolves: https://github.com/wso2/api-manager/issues/1908

Enable setCharacterEncoding property in MultipartFormDataFormatter

---

modules/kernel/src/org/apache/axis2/description/OutInAxisOperation.java
modules/kernel/src/org/apache/axis2/util/Utils.java

Due to the msgcontext having the fully qualified variable instead of the absolute url, it restricted all the service calls for the carbon console. This PR fixes it by extracting the absolute url from the fully qualified url.
Resolves : https://github.com/wso2/api-manager/issues/2313

Adds extractServicePath method to get Absolute url

---

modules/kernel/src/org/apache/axis2/deployment/Deployer.java
modules/kernel/src/org/apache/axis2/deployment/DeploymentEngine.java
modules/kernel/test/org/apache/axis2/deployment/CustomDeployerTest.java

This PR introduces a change to support custom sorting of `.car` files during deployment based on their dependencies. 
To enable this, the responsibility of sorting deployables is moved to the deployer itself. This allows each deployer to define its own sorting mechanism.

Move deployable sorting logic into deployer

---

modules/integration/test/org/apache/axis2/transport/http/NonProxyHostTest.java
modules/transport/http/src/org/apache/axis2/transport/http/AbstractHTTPSender.java
modules/transport/http/src/org/apache/axis2/transport/http/util/HTTPProxyConfigurationUtil.java

- The following improvements were done with regard to blocking mode proxy service calls
- Read the following proxy related configurations related to blocking mode from deployment.toml file
```
[transport.blocking_https]
sender.parameters.'http.proxyHost' = "<OUT_PROXY_HOST>"
sender.parameters.'http.proxyPort' = "<OUT_PROXY_PORT>"
sender.parameters.'http.nonProxyHosts' = "<OUT_PROXY_NON_HOSTS>"
```
- Introduced a new parameter called 'http.targetHosts' to define the list of hosts to which the HTTP traffic should be sent through the proxy. The idea of introducing this parameter is to handle scenarios where less backend traffic is routed via a proxy. In such a scenario, rather than defining a comprehensive list of direct call URLs under http.nonProxyHosts, this parameter allows to define …

Improve Blocking Mode Proxy Service Calls

---

modules/transport/base/src/main/java/org/apache/axis2/transport/base/AckDecision.java
modules/transport/base/src/main/java/org/apache/axis2/transport/base/AckDecisionCallback.java

Ensures onError sequences are resolved correctly by removing duplicate/invalid mediator execution paths. This prevents unexpected behavior when mediation is aborted and an error handler is invoked.
Adds callback-controlled acknowledgement for RabbitMQ inbound listener. A latch-based callback mechanism is introduced, allowing mediation to explicitly decide between ACKNOWLEDGE, SET_ROLLBACK_ONLY, or REQUEUE. This prevents premature acks and enables safe retries.
Fixes: https://github.com/wso2/product-micro-integrator/issues/4348

Add callback-based ack with timeout registry and channel abort
